on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "test/*.go"
name: terratest
jobs:
  terratest:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: "1.22.x"
      - uses: "google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70" # v2
        with:
          project_id: "library-344516"
          workload_identity_provider: "projects/270410071403/locations/global/workloadIdentityPools/github/providers/padok-gcp-library"
      - name: tfswitch
        run: |
          wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
          chmod 755 install.sh
          ./install.sh -b ~/.local/bin v1.2.2 # Last arg is the desired tfswitch version
          rm install.sh
          tfswitch -b ~/.local/bin/terraform
      - name: Test with the Go CLI
        run: go test -timeout 30s ./test
